# Generated by Django 2.2.6 on 2019-12-07 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_category_name', models.CharField(max_length=120)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceManager.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_amount', models.IntegerField()),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceManager.IncomeCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category_name', models.CharField(max_length=120)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceManager.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_amount', models.IntegerField()),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceManager.ExpenseCategory')),
            ],
        ),
    ]
