# Generated by Django 2.2.6 on 2019-12-14 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
                ('category_icon', models.CharField(default='<i class="fas fa-dollar-sign fa-7x"></i>', max_length=50)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceManager.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceManager.Budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceManager.IncomeCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
                ('category_icon', models.CharField(default='<i class="fas fa-dollar-sign fa-7x"></i>', max_length=50)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceManager.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceManager.Budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceManager.ExpenseCategory')),
            ],
        ),
    ]
