# Generated by Django 2.2.6 on 2019-11-25 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UsersManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='City', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Country', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
