# Generated by Django 2.2.6 on 2019-11-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersManager', '0002_auto_20191125_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='registration_date',
        ),
    ]
